/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models

import ai.useblackman.client.models.Message
import ai.useblackman.client.models.Provider

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param messages 
 * @param model 
 * @param provider 
 * @param maxTokens 
 * @param stop 
 * @param stream 
 * @param temperature 
 * @param topP 
 * @param metadata Optional metadata for tracking, analytics, and conditional processing. Can include session IDs, user context, feature flags, or any custom data. This metadata is logged with the request and can be used for filtering/analysis.
 */


data class CompletionRequest (

    @Json(name = "messages")
    val messages: kotlin.collections.List<Message>,

    @Json(name = "model")
    val model: kotlin.String,

    @Json(name = "provider")
    val provider: Provider,

    @Json(name = "max_tokens")
    val maxTokens: kotlin.Int? = null,

    @Json(name = "stop")
    val stop: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "stream")
    val stream: kotlin.Boolean? = null,

    @Json(name = "temperature")
    val temperature: kotlin.Float? = null,

    @Json(name = "top_p")
    val topP: kotlin.Float? = null,

    /* Optional metadata for tracking, analytics, and conditional processing. Can include session IDs, user context, feature flags, or any custom data. This metadata is logged with the request and can be used for filtering/analysis. */
    @Json(name = "metadata")
    val metadata: kotlin.Any? = null

) {


}

