/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models

import ai.useblackman.client.models.Choice
import ai.useblackman.client.models.Provider
import ai.useblackman.client.models.Usage

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param choices 
 * @param created 
 * @param id 
 * @param model 
 * @param provider 
 * @param usage 
 */


data class CompletionResponse (

    @Json(name = "choices")
    val choices: kotlin.collections.List<Choice>,

    @Json(name = "created")
    val created: kotlin.Long,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "model")
    val model: kotlin.String,

    @Json(name = "provider")
    val provider: Provider,

    @Json(name = "usage")
    val usage: Usage

) {


}

