/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param maxTokens 
 * @param stop 
 * @param stream 
 * @param temperature 
 * @param topP 
 */


data class CompletionOptions (

    @Json(name = "max_tokens")
    val maxTokens: kotlin.Int? = null,

    @Json(name = "stop")
    val stop: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "stream")
    val stream: kotlin.Boolean? = null,

    @Json(name = "temperature")
    val temperature: kotlin.Float? = null,

    @Json(name = "top_p")
    val topP: kotlin.Float? = null

) {


}

