/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models

import ai.useblackman.client.models.ContentPartOneOf
import ai.useblackman.client.models.ContentPartOneOf1
import ai.useblackman.client.models.ImageUrl

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Content part for multimodal messages (vision support)
 *
 * @param text 
 * @param type 
 * @param imageUrl 
 */


data class ContentPart (

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "type")
    val type: ContentPart.Type,

    @Json(name = "image_url")
    val imageUrl: ImageUrl

) {

    /**
     * 
     *
     * Values: text,image_url
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "text") text("text"),
        @Json(name = "image_url") image_url("image_url");
    }

}

