/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models

import ai.useblackman.client.models.ImageUrl

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param imageUrl 
 * @param type 
 */


data class ContentPartOneOf1 (

    @Json(name = "image_url")
    val imageUrl: ImageUrl,

    @Json(name = "type")
    val type: ContentPartOneOf1.Type

) {

    /**
     * 
     *
     * Values: image_url
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "image_url") image_url("image_url");
    }

}

