/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param url 
 * @param detail Optional detail level: \"auto\", \"low\", or \"high\"
 */


data class ImageUrl (

    @Json(name = "url")
    val url: kotlin.String,

    /* Optional detail level: \"auto\", \"low\", or \"high\" */
    @Json(name = "detail")
    val detail: kotlin.String? = null

) {


}

