/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param content 
 * @param role \"user\", \"assistant\", \"system\"
 */


data class Message (

    @Json(name = "content")
    val content: kotlin.String,

    /* \"user\", \"assistant\", \"system\" */
    @Json(name = "role")
    val role: kotlin.String

) {


}

