/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models

import ai.useblackman.client.models.ContentPart

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Message content can be either a simple string or an array of content parts (for vision)
 *
 */


class MessageContent (

) {


}

