/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: OpenAI,Anthropic,Gemini,Mistral,Groq
 */

@JsonClass(generateAdapter = false)
enum class Provider(val value: kotlin.String) {

    @Json(name = "OpenAI")
    OpenAI("OpenAI"),

    @Json(name = "Anthropic")
    Anthropic("Anthropic"),

    @Json(name = "Gemini")
    Gemini("Gemini"),

    @Json(name = "Mistral")
    Mistral("Mistral"),

    @Json(name = "Groq")
    Groq("Groq");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Provider) "$data" else null

        /**
         * Returns a valid [Provider] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Provider? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

