/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param avgSimilarityScore Average similarity score for cache hits
 * @param costSaved Total cost saved from cache hits
 * @param hitRate Cache hit rate as a percentage
 * @param tokensSaved Total tokens saved from cache hits
 * @param totalHits Total number of cache hits
 * @param totalMisses Total number of cache misses
 */


data class SemanticCacheStats (

    /* Average similarity score for cache hits */
    @Json(name = "avg_similarity_score")
    val avgSimilarityScore: kotlin.Double,

    /* Total cost saved from cache hits */
    @Json(name = "cost_saved")
    val costSaved: kotlin.Double,

    /* Cache hit rate as a percentage */
    @Json(name = "hit_rate")
    val hitRate: kotlin.Double,

    /* Total tokens saved from cache hits */
    @Json(name = "tokens_saved")
    val tokensSaved: kotlin.Long,

    /* Total number of cache hits */
    @Json(name = "total_hits")
    val totalHits: kotlin.Long,

    /* Total number of cache misses */
    @Json(name = "total_misses")
    val totalMisses: kotlin.Long

) {


}

