/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param enabled Whether semantic caching is enabled
 * @param similarityThreshold Similarity threshold for cache hits (0.0-1.0)
 * @param ttlSeconds Time-to-live for cache entries in seconds
 */


data class SemanticCacheConfig (

    /* Whether semantic caching is enabled */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    /* Similarity threshold for cache hits (0.0-1.0) */
    @Json(name = "similarity_threshold")
    val similarityThreshold: kotlin.Double,

    /* Time-to-live for cache entries in seconds */
    @Json(name = "ttl_seconds")
    val ttlSeconds: kotlin.Long

) {


}

