/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isPositive True for thumbs up, false for thumbs down
 * @param responseId The response ID from the completion request
 * @param metadata Optional metadata (e.g., user_agent, session_id, etc.)
 */


data class SubmitFeedbackRequest (

    /* True for thumbs up, false for thumbs down */
    @Json(name = "is_positive")
    val isPositive: kotlin.Boolean,

    /* The response ID from the completion request */
    @Json(name = "response_id")
    val responseId: kotlin.String,

    /* Optional metadata (e.g., user_agent, session_id, etc.) */
    @Json(name = "metadata")
    val metadata: kotlin.Any? = null

) {


}

