/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param completionTokens 
 * @param promptTokens 
 * @param totalTokens 
 */


data class Usage (

    @Json(name = "completion_tokens")
    val completionTokens: kotlin.Int,

    @Json(name = "prompt_tokens")
    val promptTokens: kotlin.Int,

    @Json(name = "total_tokens")
    val totalTokens: kotlin.Int

) {


}

