/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.useblackman.client.models.CompletionOptions

class CompletionOptionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CompletionOptions
        //val modelInstance = CompletionOptions()

        // to test the property `maxTokens`
        should("test maxTokens") {
            // uncomment below to test the property
            //modelInstance.maxTokens shouldBe ("TODO")
        }

        // to test the property `stop`
        should("test stop") {
            // uncomment below to test the property
            //modelInstance.stop shouldBe ("TODO")
        }

        // to test the property `stream`
        should("test stream") {
            // uncomment below to test the property
            //modelInstance.stream shouldBe ("TODO")
        }

        // to test the property `temperature`
        should("test temperature") {
            // uncomment below to test the property
            //modelInstance.temperature shouldBe ("TODO")
        }

        // to test the property `topP`
        should("test topP") {
            // uncomment below to test the property
            //modelInstance.topP shouldBe ("TODO")
        }

    }
}
