/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.useblackman.client.models.ImageUrl

class ImageUrlTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ImageUrl
        //val modelInstance = ImageUrl()

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `detail` - Optional detail level: \"auto\", \"low\", or \"high\"
        should("test detail") {
            // uncomment below to test the property
            //modelInstance.detail shouldBe ("TODO")
        }

    }
}
