/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.useblackman.client.models.InvalidateResponse

class InvalidateResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvalidateResponse
        //val modelInstance = InvalidateResponse()

        // to test the property `message` - Success message
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
