/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.useblackman.client.models.MessageContent
import ai.useblackman.client.models.ContentPart

class MessageContentTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MessageContent
        //val modelInstance = MessageContent()

    }
}
