/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.useblackman.client.models.SemanticCacheConfig

class SemanticCacheConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SemanticCacheConfig
        //val modelInstance = SemanticCacheConfig()

        // to test the property `enabled` - Whether semantic caching is enabled
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `similarityThreshold` - Similarity threshold for cache hits (0.0-1.0)
        should("test similarityThreshold") {
            // uncomment below to test the property
            //modelInstance.similarityThreshold shouldBe ("TODO")
        }

        // to test the property `ttlSeconds` - Time-to-live for cache entries in seconds
        should("test ttlSeconds") {
            // uncomment below to test the property
            //modelInstance.ttlSeconds shouldBe ("TODO")
        }

    }
}
