/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.useblackman.client.models.SubmitFeedbackRequest

class SubmitFeedbackRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubmitFeedbackRequest
        //val modelInstance = SubmitFeedbackRequest()

        // to test the property `isPositive` - True for thumbs up, false for thumbs down
        should("test isPositive") {
            // uncomment below to test the property
            //modelInstance.isPositive shouldBe ("TODO")
        }

        // to test the property `responseId` - The response ID from the completion request
        should("test responseId") {
            // uncomment below to test the property
            //modelInstance.responseId shouldBe ("TODO")
        }

        // to test the property `metadata` - Optional metadata (e.g., user_agent, session_id, etc.)
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
