/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.useblackman.client.models.CompletionRequest
import ai.useblackman.client.models.CompletionResponse

import com.squareup.moshi.Json

import ai.useblackman.client.infrastructure.ApiClient
import ai.useblackman.client.infrastructure.ApiResponse
import ai.useblackman.client.infrastructure.ClientException
import ai.useblackman.client.infrastructure.ClientError
import ai.useblackman.client.infrastructure.ServerException
import ai.useblackman.client.infrastructure.ServerError
import ai.useblackman.client.infrastructure.MultiValueMap
import ai.useblackman.client.infrastructure.PartConfig
import ai.useblackman.client.infrastructure.RequestConfig
import ai.useblackman.client.infrastructure.RequestMethod
import ai.useblackman.client.infrastructure.ResponseType
import ai.useblackman.client.infrastructure.Success
import ai.useblackman.client.infrastructure.toMultiValue

class CompletionsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://app.useblackman.ai/v1")
        }
    }

    /**
     * POST /v1/completions
     * 
     * 
     * @param completionRequest 
     * @param xProviderApiKey Optional provider API key to override stored or system keys (optional)
     * @return CompletionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun completions(completionRequest: CompletionRequest, xProviderApiKey: kotlin.String? = null) : CompletionResponse {
        val localVarResponse = completionsWithHttpInfo(completionRequest = completionRequest, xProviderApiKey = xProviderApiKey)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CompletionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/completions
     * 
     * 
     * @param completionRequest 
     * @param xProviderApiKey Optional provider API key to override stored or system keys (optional)
     * @return ApiResponse<CompletionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun completionsWithHttpInfo(completionRequest: CompletionRequest, xProviderApiKey: kotlin.String?) : ApiResponse<CompletionResponse?> {
        val localVariableConfig = completionsRequestConfig(completionRequest = completionRequest, xProviderApiKey = xProviderApiKey)

        return request<CompletionRequest, CompletionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation completions
     *
     * @param completionRequest 
     * @param xProviderApiKey Optional provider API key to override stored or system keys (optional)
     * @return RequestConfig
     */
    fun completionsRequestConfig(completionRequest: CompletionRequest, xProviderApiKey: kotlin.String?) : RequestConfig<CompletionRequest> {
        val localVariableBody = completionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xProviderApiKey?.apply { localVariableHeaders["X-Provider-Api-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/completions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
