/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.useblackman.client.models.SubmitFeedbackRequest
import ai.useblackman.client.models.SubmitFeedbackResponse

import com.squareup.moshi.Json

import ai.useblackman.client.infrastructure.ApiClient
import ai.useblackman.client.infrastructure.ApiResponse
import ai.useblackman.client.infrastructure.ClientException
import ai.useblackman.client.infrastructure.ClientError
import ai.useblackman.client.infrastructure.ServerException
import ai.useblackman.client.infrastructure.ServerError
import ai.useblackman.client.infrastructure.MultiValueMap
import ai.useblackman.client.infrastructure.PartConfig
import ai.useblackman.client.infrastructure.RequestConfig
import ai.useblackman.client.infrastructure.RequestMethod
import ai.useblackman.client.infrastructure.ResponseType
import ai.useblackman.client.infrastructure.Success
import ai.useblackman.client.infrastructure.toMultiValue

class FeedbackApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://app.useblackman.ai/v1")
        }
    }

    /**
     * POST /v1/feedback
     * Submit feedback for a completion response
     * 
     * @param submitFeedbackRequest 
     * @return SubmitFeedbackResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun submitFeedback(submitFeedbackRequest: SubmitFeedbackRequest) : SubmitFeedbackResponse {
        val localVarResponse = submitFeedbackWithHttpInfo(submitFeedbackRequest = submitFeedbackRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SubmitFeedbackResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/feedback
     * Submit feedback for a completion response
     * 
     * @param submitFeedbackRequest 
     * @return ApiResponse<SubmitFeedbackResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun submitFeedbackWithHttpInfo(submitFeedbackRequest: SubmitFeedbackRequest) : ApiResponse<SubmitFeedbackResponse?> {
        val localVariableConfig = submitFeedbackRequestConfig(submitFeedbackRequest = submitFeedbackRequest)

        return request<SubmitFeedbackRequest, SubmitFeedbackResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation submitFeedback
     *
     * @param submitFeedbackRequest 
     * @return RequestConfig
     */
    fun submitFeedbackRequestConfig(submitFeedbackRequest: SubmitFeedbackRequest) : RequestConfig<SubmitFeedbackRequest> {
        val localVariableBody = submitFeedbackRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/feedback",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
