/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.useblackman.client.models.InvalidateResponse
import ai.useblackman.client.models.SemanticCacheConfig
import ai.useblackman.client.models.SemanticCacheStats

import com.squareup.moshi.Json

import ai.useblackman.client.infrastructure.ApiClient
import ai.useblackman.client.infrastructure.ApiResponse
import ai.useblackman.client.infrastructure.ClientException
import ai.useblackman.client.infrastructure.ClientError
import ai.useblackman.client.infrastructure.ServerException
import ai.useblackman.client.infrastructure.ServerError
import ai.useblackman.client.infrastructure.MultiValueMap
import ai.useblackman.client.infrastructure.PartConfig
import ai.useblackman.client.infrastructure.RequestConfig
import ai.useblackman.client.infrastructure.RequestMethod
import ai.useblackman.client.infrastructure.ResponseType
import ai.useblackman.client.infrastructure.Success
import ai.useblackman.client.infrastructure.toMultiValue

class SemanticCacheApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://app.useblackman.ai/v1")
        }
    }

    /**
     * GET /v1/semantic-cache/config
     * Get semantic cache configuration for the current account
     * 
     * @return SemanticCacheConfig
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getConfig() : SemanticCacheConfig {
        val localVarResponse = getConfigWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SemanticCacheConfig
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/semantic-cache/config
     * Get semantic cache configuration for the current account
     * 
     * @return ApiResponse<SemanticCacheConfig?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getConfigWithHttpInfo() : ApiResponse<SemanticCacheConfig?> {
        val localVariableConfig = getConfigRequestConfig()

        return request<Unit, SemanticCacheConfig>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getConfig
     *
     * @return RequestConfig
     */
    fun getConfigRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/semantic-cache/config",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/semantic-cache/stats
     * Get semantic cache statistics including hit rate and savings
     * 
     * @return SemanticCacheStats
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getStats() : SemanticCacheStats {
        val localVarResponse = getStatsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SemanticCacheStats
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/semantic-cache/stats
     * Get semantic cache statistics including hit rate and savings
     * 
     * @return ApiResponse<SemanticCacheStats?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getStatsWithHttpInfo() : ApiResponse<SemanticCacheStats?> {
        val localVariableConfig = getStatsRequestConfig()

        return request<Unit, SemanticCacheStats>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getStats
     *
     * @return RequestConfig
     */
    fun getStatsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/semantic-cache/stats",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/semantic-cache/invalidate
     * Invalidate all cache entries for the current account
     * 
     * @return InvalidateResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun invalidateAll() : InvalidateResponse {
        val localVarResponse = invalidateAllWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as InvalidateResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/semantic-cache/invalidate
     * Invalidate all cache entries for the current account
     * 
     * @return ApiResponse<InvalidateResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun invalidateAllWithHttpInfo() : ApiResponse<InvalidateResponse?> {
        val localVariableConfig = invalidateAllRequestConfig()

        return request<Unit, InvalidateResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation invalidateAll
     *
     * @return RequestConfig
     */
    fun invalidateAllRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/semantic-cache/invalidate",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /v1/semantic-cache/config
     * Update semantic cache configuration for the current account
     * 
     * @param semanticCacheConfig 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateConfig(semanticCacheConfig: SemanticCacheConfig) : Unit {
        val localVarResponse = updateConfigWithHttpInfo(semanticCacheConfig = semanticCacheConfig)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /v1/semantic-cache/config
     * Update semantic cache configuration for the current account
     * 
     * @param semanticCacheConfig 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun updateConfigWithHttpInfo(semanticCacheConfig: SemanticCacheConfig) : ApiResponse<Unit?> {
        val localVariableConfig = updateConfigRequestConfig(semanticCacheConfig = semanticCacheConfig)

        return request<SemanticCacheConfig, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateConfig
     *
     * @param semanticCacheConfig 
     * @return RequestConfig
     */
    fun updateConfigRequestConfig(semanticCacheConfig: SemanticCacheConfig) : RequestConfig<SemanticCacheConfig> {
        val localVariableBody = semanticCacheConfig
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/v1/semantic-cache/config",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
