/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.useblackman.client.apis.CompletionsApi
import ai.useblackman.client.models.CompletionRequest
import ai.useblackman.client.models.CompletionResponse

class CompletionsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CompletionsApi
        //val apiInstance = CompletionsApi()

        // to test completions
        should("test completions") {
            // uncomment below to test completions
            //val completionRequest : CompletionRequest =  // CompletionRequest | 
            //val xProviderApiKey : kotlin.String = xProviderApiKey_example // kotlin.String | Optional provider API key to override stored or system keys
            //val result : CompletionResponse = apiInstance.completions(completionRequest, xProviderApiKey)
            //result shouldBe ("TODO")
        }

    }
}
