/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.useblackman.client.apis.FeedbackApi
import ai.useblackman.client.models.SubmitFeedbackRequest
import ai.useblackman.client.models.SubmitFeedbackResponse

class FeedbackApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FeedbackApi
        //val apiInstance = FeedbackApi()

        // to test submitFeedback
        should("test submitFeedback") {
            // uncomment below to test submitFeedback
            //val submitFeedbackRequest : SubmitFeedbackRequest =  // SubmitFeedbackRequest | 
            //val result : SubmitFeedbackResponse = apiInstance.submitFeedback(submitFeedbackRequest)
            //result shouldBe ("TODO")
        }

    }
}
