/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.useblackman.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.useblackman.client.apis.SemanticCacheApi
import ai.useblackman.client.models.InvalidateResponse
import ai.useblackman.client.models.SemanticCacheConfig
import ai.useblackman.client.models.SemanticCacheStats

class SemanticCacheApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SemanticCacheApi
        //val apiInstance = SemanticCacheApi()

        // to test getConfig
        should("test getConfig") {
            // uncomment below to test getConfig
            //val result : SemanticCacheConfig = apiInstance.getConfig()
            //result shouldBe ("TODO")
        }

        // to test getStats
        should("test getStats") {
            // uncomment below to test getStats
            //val result : SemanticCacheStats = apiInstance.getStats()
            //result shouldBe ("TODO")
        }

        // to test invalidateAll
        should("test invalidateAll") {
            // uncomment below to test invalidateAll
            //val result : InvalidateResponse = apiInstance.invalidateAll()
            //result shouldBe ("TODO")
        }

        // to test updateConfig
        should("test updateConfig") {
            // uncomment below to test updateConfig
            //val semanticCacheConfig : SemanticCacheConfig =  // SemanticCacheConfig | 
            //apiInstance.updateConfig(semanticCacheConfig)
        }

    }
}
